// <auto-generated />
using System;
using AracServisTakipSistemi.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AracServisTakipSistemi.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260804083447_BolgeYapisi")]
    partial class BolgeYapisi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AracServisTakipSistemi.Entities.Entities.Arac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("AracTipi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("BakimdaMi")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ErpAracKartNo")
                        .HasColumnType("longtext");

                    b.Property<bool>("ErpyeAktarildiMi")
                        .HasColumnType("tinyint(1)");

                    b.Property<double>("GuncelKm")
                        .HasColumnType("double");

                    b.Property<int>("KapasiteSayisi")
                        .HasColumnType("int");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ModelYili")
                        .HasColumnType("int");

                    b.Property<string>("MotorNo")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("MuayeneTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Plaka")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SasiNo")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("SatinAlmaTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("SigortaBitisTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("SoforPersonelId")
                        .HasColumnType("int");

                    b.Property<int?>("SubeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SoforPersonelId");

                    b.ToTable("Araclar");
                });

            modelBuilder.Entity("AracServisTakipSistemi.Entities.Entities.AracArizaKaydi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("AracId")
                        .HasColumnType("int");

                    b.Property<double>("ArizaAnindakiKm")
                        .HasColumnType("double");

                    b.Property<DateTime>("ArizaTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ArizaTuru")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("OnarimMaliyeti")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AracId");

                    b.ToTable("AracArizaKayitlari");
                });

            modelBuilder.Entity("AracServisTakipSistemi.Entities.Entities.BakimKaydi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("longtext");

                    b.Property<int>("AracId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BakimTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("BakimTuru")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Maliyet")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SonrakiBakimKm")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SonrakiBakimTarihi")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AracId");

                    b.ToTable("BakimKayitlari");
                });

            modelBuilder.Entity("AracServisTakipSistemi.Entities.Entities.Bolge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("longtext");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("BolgeAdi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BolgeKodu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("KapasiteTamponu")
                        .HasColumnType("int");

                    b.Property<double?>("MerkezBoylam")
                        .HasColumnType("double");

                    b.Property<double?>("MerkezEnlem")
                        .HasColumnType("double");

                    b.Property<int>("MinPersonelEsigi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Bolgeler");
                });

            modelBuilder.Entity("AracServisTakipSistemi.Entities.Entities.Personel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("AnneAdi")
                        .HasColumnType("longtext");

                    b.Property<string>("BabaAdi")
                        .HasColumnType("longtext");

                    b.Property<int?>("BolgeId")
                        .HasColumnType("int");

                    b.Property<string>("Cinsiyet")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DogumTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Eposta")
                        .HasColumnType("longtext");

                    b.Property<string>("ErpPersonelKodu")
                        .HasColumnType("longtext");

                    b.Property<bool>("ErpyeAktarildiMi")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("IseGirisTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("IstenCikisTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("KanGrubu")
                        .HasColumnType("longtext");

                    b.Property<int>("PersonelTuru")
                        .HasColumnType("int");

                    b.Property<int>("ServisDurumu")
                        .HasColumnType("int");

                    b.Property<string>("SicilNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("SubeId")
                        .HasColumnType("int");

                    b.Property<string>("Telefon")
                        .HasColumnType("longtext");

                    b.Property<int?>("VardiyaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BolgeId");

                    b.HasIndex("VardiyaId");

                    b.ToTable("Personeller");
                });

            modelBuilder.Entity("AracServisTakipSistemi.Entities.Entities.PersonelAdres", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdresTuru")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ApartmanNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("Boylam")
                        .HasColumnType("double");

                    b.Property<string>("DisKapiNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double?>("Enlem")
                        .HasColumnType("double");

                    b.Property<DateTime?>("GeocodeTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IlceAdi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Mahalle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<string>("Sehir")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Semt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Sokak")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PersonelId");

                    b.ToTable("PersonelAdresleri");
                });

            modelBuilder.Entity("AracServisTakipSistemi.Entities.Entities.RiskSkoru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AracId")
                        .HasColumnType("int");

                    b.Property<DateTime>("HesaplamaTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OnerilenAksiyon")
                        .HasColumnType("longtext");

                    b.Property<int>("RiskSeviyesi")
                        .HasColumnType("int");

                    b.Property<decimal>("SkorDegeri")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("AracId");

                    b.ToTable("RiskSkorlari");
                });

            modelBuilder.Entity("AracServisTakipSistemi.Entities.Entities.Rota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("AracId")
                        .HasColumnType("int");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<bool>("ErpyeAktarildiMi")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("RotaTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TahminiSureDk")
                        .HasColumnType("int");

                    b.Property<double>("ToplamMesafeKm")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("AracId");

                    b.ToTable("Rotalar");
                });

            modelBuilder.Entity("AracServisTakipSistemi.Entities.Entities.RotaBolge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BolgeId")
                        .HasColumnType("int");

                    b.Property<int>("RotaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BolgeId");

                    b.HasIndex("RotaId");

                    b.ToTable("RotaBolgeleri");
                });

            modelBuilder.Entity("AracServisTakipSistemi.Entities.Entities.RotaDuragi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<int>("RotaId")
                        .HasColumnType("int");

                    b.Property<int>("SiraNo")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("TahminiVarisSaati")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.HasIndex("PersonelId");

                    b.HasIndex("RotaId");

                    b.ToTable("RotaDuraklari");
                });

            modelBuilder.Entity("AracServisTakipSistemi.Entities.Entities.SemtReferans", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("MerkezBoylam")
                        .HasColumnType("double");

                    b.Property<double>("MerkezEnlem")
                        .HasColumnType("double");

                    b.Property<string>("SemtAdi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SemtReferanslari");
                });

            modelBuilder.Entity("AracServisTakipSistemi.Entities.Entities.Vardiya", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("tinyint(1)");

                    b.Property<TimeSpan>("BaslangicSaati")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("BitisSaati")
                        .HasColumnType("time(6)");

                    b.Property<string>("VardiyaAdi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Vardiyalar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AktifMi = true,
                            BaslangicSaati = new TimeSpan(0, 8, 30, 0, 0),
                            BitisSaati = new TimeSpan(0, 18, 0, 0, 0),
                            VardiyaAdi = "Sabah"
                        });
                });

            modelBuilder.Entity("AracServisTakipSistemi.Entities.Entities.Arac", b =>
                {
                    b.HasOne("AracServisTakipSistemi.Entities.Entities.Personel", "SoforPersonel")
                        .WithMany()
                        .HasForeignKey("SoforPersonelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SoforPersonel");
                });

            modelBuilder.Entity("AracServisTakipSistemi.Entities.Entities.AracArizaKaydi", b =>
                {
                    b.HasOne("AracServisTakipSistemi.Entities.Entities.Arac", "Arac")
                        .WithMany("ArizaKayitlari")
                        .HasForeignKey("AracId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arac");
                });

            modelBuilder.Entity("AracServisTakipSistemi.Entities.Entities.BakimKaydi", b =>
                {
                    b.HasOne("AracServisTakipSistemi.Entities.Entities.Arac", "Arac")
                        .WithMany("BakimKayitlari")
                        .HasForeignKey("AracId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arac");
                });

            modelBuilder.Entity("AracServisTakipSistemi.Entities.Entities.Personel", b =>
                {
                    b.HasOne("AracServisTakipSistemi.Entities.Entities.Bolge", "Bolge")
                        .WithMany("Personeller")
                        .HasForeignKey("BolgeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AracServisTakipSistemi.Entities.Entities.Vardiya", "Vardiya")
                        .WithMany("Personeller")
                        .HasForeignKey("VardiyaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Bolge");

                    b.Navigation("Vardiya");
                });

            modelBuilder.Entity("AracServisTakipSistemi.Entities.Entities.PersonelAdres", b =>
                {
                    b.HasOne("AracServisTakipSistemi.Entities.Entities.Personel", "Personel")
                        .WithMany("Adresler")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("AracServisTakipSistemi.Entities.Entities.RiskSkoru", b =>
                {
                    b.HasOne("AracServisTakipSistemi.Entities.Entities.Arac", "Arac")
                        .WithMany("RiskSkorlari")
                        .HasForeignKey("AracId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arac");
                });

            modelBuilder.Entity("AracServisTakipSistemi.Entities.Entities.Rota", b =>
                {
                    b.HasOne("AracServisTakipSistemi.Entities.Entities.Arac", "Arac")
                        .WithMany("Rotalar")
                        .HasForeignKey("AracId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arac");
                });

            modelBuilder.Entity("AracServisTakipSistemi.Entities.Entities.RotaBolge", b =>
                {
                    b.HasOne("AracServisTakipSistemi.Entities.Entities.Bolge", "Bolge")
                        .WithMany("RotaBolgeleri")
                        .HasForeignKey("BolgeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AracServisTakipSistemi.Entities.Entities.Rota", "Rota")
                        .WithMany("Bolgeler")
                        .HasForeignKey("RotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bolge");

                    b.Navigation("Rota");
                });

            modelBuilder.Entity("AracServisTakipSistemi.Entities.Entities.RotaDuragi", b =>
                {
                    b.HasOne("AracServisTakipSistemi.Entities.Entities.Personel", "Personel")
                        .WithMany("RotaDuraklari")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AracServisTakipSistemi.Entities.Entities.Rota", "Rota")
                        .WithMany("Duraklar")
                        .HasForeignKey("RotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");

                    b.Navigation("Rota");
                });

            modelBuilder.Entity("AracServisTakipSistemi.Entities.Entities.Arac", b =>
                {
                    b.Navigation("ArizaKayitlari");

                    b.Navigation("BakimKayitlari");

                    b.Navigation("RiskSkorlari");

                    b.Navigation("Rotalar");
                });

            modelBuilder.Entity("AracServisTakipSistemi.Entities.Entities.Bolge", b =>
                {
                    b.Navigation("Personeller");

                    b.Navigation("RotaBolgeleri");
                });

            modelBuilder.Entity("AracServisTakipSistemi.Entities.Entities.Personel", b =>
                {
                    b.Navigation("Adresler");

                    b.Navigation("RotaDuraklari");
                });

            modelBuilder.Entity("AracServisTakipSistemi.Entities.Entities.Rota", b =>
                {
                    b.Navigation("Bolgeler");

                    b.Navigation("Duraklar");
                });

            modelBuilder.Entity("AracServisTakipSistemi.Entities.Entities.Vardiya", b =>
                {
                    b.Navigation("Personeller");
                });
#pragma warning restore 612, 618
        }
    }
}
